version: 2

sources:
  - name: tpch_sample
    database: DEV_EDW
    schema: STAGING
    tables:
      - name: LINEITEM
      - name: CUSTOMER
      - name: ORDERS
      - name: PARTSUPP
      - name: SUPPLIER
      - name: PART
      - name: NATION
      - name: REGION
